//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VideoProcessor.rc
//
#define IDD_VIDEOPROCESSOR_DIALOG       102
#define IDR_MAINFRAME                   128
#define IDB_CIE1931XY                   129
#define IDR_ACCELERATOR1                130
#define IDB_LOGO                        133
#define IDC_CAPTURE_DEVICE_COMBO        1000
#define IDC_RENDERER_NOMINAL_RANGE_COMBO 1001
#define IDC_RENDERER_TRANSFER_FUNCTION_COMBO 1002
#define IDC_RENDERER_TRANSFER_MATRIX_COMBO 1003
#define IDC_RENDERER_PRIMARIES_COMBO    1004
#define IDC_CAPTURE_INPUT_COMBO         1005
#define IDC_FULL_SCREEN_BUTTON          1006
#define IDC_CAPTURE_DEVICE_OTHER_GROUP  1007
#define IDC_RENDERER_RESTART_BUTTON     1008
#define IDC_RENDERER_RESET_BUTTON       1009
#define IDC_RENDERER_TIMESTAMP_COMBO    1010
#define IDC_RENDERER_COMBO              1011
#define IDC_RENDERER_BOX                1017
#define IDC_VIDEO_EOTF_STATIC           1018
#define IDC_HDR_DML_STATIC              1027
#define IDC_HDR_MAX_CLL_STATIC          1029
#define IDC_HDR_MAX_FALL_STATIC         1030
#define IDC_VIDEO_COLORSPACE_STATIC     1031
#define IDC_INPUT_LOCKED_STATIC         1032
#define IDC_VIDEO_DATA_GROUP            1035
#define IDC_RENDERER_GROUP              1036
#define IDC_VIDEO_SIGNAL_GROUP          1037
#define IDC_STATIC_HDR_DATA_GROUP       1038
#define IDC_CAPTURE_DEVICE_OTHER_LIST   1039
#define IDC_INPUT_DISPLAY_MODE_STATIC   1040
#define IDC_INPUT_ENCODING_STATIC       1041
#define IDC_VIDEO_DISPLAY_MODE_STATIC   1042
#define IDC_VIDEO_PIXEL_FORMAT_STATIC   1043
#define IDC_HDMI_GROUP                  1044
#define IDC_INPUT_BIT_DEPTH_STATIC      1045
#define IDC_CAPTURE_STATE_STATIC        1046
#define IDC_CIE1931XY_GRAPH             1047
#define IDC_CLOCK_GROUP                 1048
#define IDC_VIDEO_VALID_STATIC          1049
#define IDC_RENDERER_STATE_STATIC       1050
#define IDC_RENDERER_VIDEO_FRAME_QUEUE_SIZE_STATIC 1051
#define IDC_RENDERER_VIDEO_FRAME_QUEUE_SIZE_MAX_EDIT 1052
#define IDC_RENDERER_VIDEO_FRAME_USE_QUEUE_CHECK 1053
#define IDC_TIMING_CLOCK_FRAME_OFFSET_EDIT 1054
#define IDC_RENDERER_NAME_STATIC        1055
#define IDC_RENDERER_DETAIL_STRING_STATIC 1055
#define IDC_TIMING_CLOCK_DESCRIPTION_STATIC 1056
#define IDC_LATENCY_CAPTURE_STATIC      1057
#define IDC_STATIC_LATENCY_GROUP        1058
#define IDC_LATENCY_TO_VP_RENDERER_STATIC 1059
#define IDC_LATENCY_TO_DS_RENDERER_STATIC 1060
#define IDC_RENDERER_DROPPED_FRAME_COUNT_STATIC 1061
#define IDC_TIMING_CLOCK_FRAME_OFFSET_AUTO_CHECK 1062
#define IDC_INPUT_VIDEO_FRAME_COUNT_STATIC 1063
#define IDC_INPUT_VIDEO_FRAME_MISSED_STATIC 1064
#define IDC_RENDERER_RESET_AUTO_CHECK   1065
#define ID_COMMAND_FULLSCREEN_TOGGLE    32772
#define ID_COMMAND_FULLSCREEN_EXIT      32778
#define ID_COMMAND_RENDERER_RESET       32780

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         1067
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
